baseURL: /
author: René Dario Herrera
copyright: 
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
ignoreErrors: error-remote-getjson
theme: hugo-paper
title: Paper
params:
  github: 
  instagram: uaz_coe
  twitter: UAZCancer_COE
menu:
  main:
    - identifier: cancer_statistics
      name: Cancer Statistics
      url: /cancer_statistics/
      weight: 10
    - identifier: demographics
      name: Demographics
      url: /demographics/
      weight: 10
taxonomies:
  category: categories
  series: series
  tag: tags
privacy:
  instagram:
    disabled: no
    simple: yes
  twitter:
    disabled: no
    enableDNT: yes
    simple: yes
  vimeo:
    disabled: no
    simple: yes
  youtube:
    disabled: no
    privacyEnhanced: yes
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes

markup:
  goldmark:
    renderer:
      unsafe: true
